version: "3.8"

services:
  osrm:
    image: osrm/osrm-backend:latest
    command: osrm-routed --algorithm mld /data/pakistan-latest.osrm
    volumes:
      - ./data:/data
    ports:
      - "5000:5000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - osrm
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
